### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Offworld92** [DarkPacks/ZenStages#1]
Whilst the Craft Tweaker portion is being updated, is there any way we could get a temporary .txt documentation document? It would help a lot!

**Comment by artdude543** [comment]
The docs are being created/updated. We are changing the API a lot so I'm making sure the API is locked down before releasing the docs.

**Comment by Offworld92** [comment]
@artdude543 Thank you for the heads up! I'm looking forward to the full release. Working on a Civ5/SevTech inspired mod pack and I think Zen Stages would go a long way in helping me to develop it.

**Comment by artdude543** [comment]
Now Live :) http://crafttweaker.readthedocs.io/en/latest/#Mods/GameStages/ZenStages/ZenStages/
