### ISSUE TITLE
ModId issue

### ISSUE THREAD

**Issue by specklogan** [DarkPacks/ZenStages#9]
Forge : 2847
Crafttweaker : 4.1.20.586
Zenstages : 0.5.0

I'm using the addModId method where you're able to provide certain items which won't be added to the stage, and it keeps throwing off errors. 
Here's the error that it gives me : https://pastebin.com/mTtcxdkq

I've followed the example that was in the crafttweaker docs and I haven't been able to make it work, specifically this example "TestStage.addModId("bloodmagic", [<bloodmagic:someitem>]);" The one I put in has the same format and it doesn't work, "Stage5.addModId("mekanism", [<mekanism:cardboardbox>]);"

My script that is doing the staging is here : https://pastebin.com/1p6PGmns
And the script that contains the static variables for the stages is here : https://pastebin.com/ByFwW4H2

I was wondering what I was doing wrong or if it was a potential bug.

**Comment by sam-kirby** [comment]
The signature of `addModId` is:
```java
public Stage addModId(String modId, @Optional(valueBoolean = false) boolean stageRecipesWithItems, @Optional IIngredient... overrides)
```

The second argument should be a boolean that dictates whether the recipes are staged along with the items. If you want to keep the default behaviour, your script should be changed to the following:

```zs
Stage5.addModId("mekanism", false, [<mekanism:cardboardbox>]);
```

Please let me know if this solves your issue.

**Comment by specklogan** [comment]
Yes this worked, thank you so much.
